using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class HandStatusModel {
    [RealtimeProperty(1, true)]
    public Vector3    _position = Vector3.zero;

    [RealtimeProperty(2, true)]
    public Quaternion _rotation = Quaternion.identity;

    [RealtimeProperty(3, true)]
    public bool _triggerPressed = false;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class HandStatusModel : RealtimeModel {
    public UnityEngine.Vector3 position {
        get {
            return _positionProperty.value;
        }
        set {
            if (_positionProperty.value == value) return;
            _positionProperty.value = value;
            InvalidateReliableLength();
        }
    }
    
    public UnityEngine.Quaternion rotation {
        get {
            return _rotationProperty.value;
        }
        set {
            if (_rotationProperty.value == value) return;
            _rotationProperty.value = value;
            InvalidateReliableLength();
        }
    }
    
    public bool triggerPressed {
        get {
            return _triggerPressedProperty.value;
        }
        set {
            if (_triggerPressedProperty.value == value) return;
            _triggerPressedProperty.value = value;
            InvalidateReliableLength();
        }
    }
    
    public enum PropertyID : uint {
        Position = 1,
        Rotation = 2,
        TriggerPressed = 3,
    }
    
    #region Properties
    
    private ReliableProperty<UnityEngine.Vector3> _positionProperty;
    
    private ReliableProperty<UnityEngine.Quaternion> _rotationProperty;
    
    private ReliableProperty<bool> _triggerPressedProperty;
    
    #endregion
    
    public HandStatusModel() : base(null) {
        _positionProperty = new ReliableProperty<UnityEngine.Vector3>(1, _position);
        _rotationProperty = new ReliableProperty<UnityEngine.Quaternion>(2, _rotation);
        _triggerPressedProperty = new ReliableProperty<bool>(3, _triggerPressed);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _positionProperty.UnsubscribeCallback();
        _rotationProperty.UnsubscribeCallback();
        _triggerPressedProperty.UnsubscribeCallback();
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _positionProperty.WriteLength(context);
        length += _rotationProperty.WriteLength(context);
        length += _triggerPressedProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _positionProperty.Write(stream, context);
        writes |= _rotationProperty.Write(stream, context);
        writes |= _triggerPressedProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Position: {
                    changed = _positionProperty.Read(stream, context);
                    break;
                }
                case (uint) PropertyID.Rotation: {
                    changed = _rotationProperty.Read(stream, context);
                    break;
                }
                case (uint) PropertyID.TriggerPressed: {
                    changed = _triggerPressedProperty.Read(stream, context);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _position = position;
        _rotation = rotation;
        _triggerPressed = triggerPressed;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
