using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class HandStatusModel {
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class HandStatusModel : RealtimeModel {
    public HandStatusModel() : base(null) {
    }
    
    protected override int WriteLength(StreamContext context) {
        return 0;
    }
    protected override void Write(WriteStream stream, StreamContext context) {
    }
    protected override void Read(ReadStream stream, StreamContext context) {
    }
    private void UpdateBackingFields() {
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
